#pragma once

enum CAM_CMD { CMD_RIGHT=0, CMD_LEFT, CMD_UP, CMD_DOWN, CMD_HOME, CMD_ADD_BRIGHT, CMD_DEC_BRIGHT, 
			   CMD_STD_BRIGHT, CMD_STD_CONTRAST, CMD_DEC_CONTRAST, CMD_ADD_CONTRAST,
			   CMD_STD_COMPRESS, CMD_SPD_COMPRESS, CMD_QUALITY_COMPRESS, CMD_TILT_SCAN,
			   CMD_PAN_SCAN, CMD_PIXEL_D1, CMD_PIXEL_VGA, CMD_PIXEL_CIF, CMD_PIXEL_QVGA,
			   CMD_PIXEL_QCIF, CMD_PIXEL_VGA_DEC_16, CMD_PIXEL_QQVGA, CMD_SHOWTITLE,
			   CMD_SET_STREAM_TYPE_JPEG, CMD_SET_STREAM_TYPE_H264, CMD_GET_USER_COUNT,
			   CMD_MOUSE_DOWN_AND_UP, CMD_GET_FEATURE, CMD_PIXEL_720P, CMD_PIXEL_1080P,
			   CMD_ADD_SATURATION, CMD_DEC_SATURATION, CMD_STD_SATURATION, 
			   CMD_ADD_HUE, CMD_DEC_HUE, CMD_STD_HUE, 
			   CMD_ADD_SHARPNESS, CMD_DEC_SHARPNESS, CMD_STD_SHARPNESS,
			   CMD_PANTILT_ZOOM_TELE, CMD_PANTILT_ZOOM_WIDE, 
			   CMD_PAN_SPEED_DEC, CMD_PAN_SPEED_INC, CMD_TILT_SPEED_DEC, CMD_TILT_SPEED_INC, 
			   CMD_PANTILT_STOP, 
			   CMD_SET_PREPOS, CMD_CLEAR_PREPOS, CMD_GOTO_PREPOS };

struct _MOUSE_DOWN_AND_UP_INFO
{
	int mouseDownX;
	int mouseDownY;
	int mouseUpX;
	int mouseUpY;
};
