#pragma once

enum VILAR_EVENT { CONNECTION_ESTABLISHED = 0, CONNECTION_CLOSED, CONNECT_FAILED, ITEM_REMOVED, RESOLUTION_CHANGED, NEED_DECRYPT_KEY,
	RECORD_STARTED, RECORD_STOPPED, USER_COUNT_ACQUIRED, FRAME_RENDERING, FRAME_RENDERED, IMAGE_CAPTURE_SUCCEED, IMAGE_CAPTURE_FAILED, 
	BUFFER_INCREASED, BUFFER_EMPTY, LAST_EVENT };

enum CONNECTION_CLOSED_PARAM { CLOSED_NOERROR = 0, NET_ERROR, RECV_TIMEOUT, AUTHORIZATION_FAILED };

struct VILAR_EVENT_PARAM
{
	long index;
	void * param;
};

struct VIDEO_RESOLUTION_INFO
{
	int width;
	int height;
};

struct FRAME_TIMESTAMP_INFO
{
	unsigned __int64 timestamp;
	unsigned __int64 nextTimestamp;
};
