######################################################################
# Automatically generated by qmake (2.01a) ?? 1? 5 22:51:23 2013
######################################################################

TEMPLATE = app
TARGET = radar
DEPENDPATH += .
INCLUDEPATH += .
QT += opengl

# Input
HEADERS += glwidget.h \
           radar_ppi.h \ 
    global.h
SOURCES += glwidget.cpp \
           radar_ppi.cpp \
           main.cpp
RESOURCES +=

DESTDIR = ./

